### ISSUE TITLE
drn_d_105-12b40979.pth

### ISSUE THREAD

**Issue by gong-lei** [mil-tokyo/MCD_DA#29]
`(pytorch1.1) zgm@zgm-icv:~/Lufei/MCD_DA/segmentation$ python adapt_trainer.py gta city --net drn_d_105
Downloading: "https://tigress-web.princeton.edu/~fy/drn/models/drn_d_105-12b40979.pth" to /home/zgm/.cache/torch/checkpoints/drn_d_105-12b40979.pth
Traceback (most recent call last):
  File "adapt_trainer.py", line 69, in <module>
    is_data_parallel=args.is_data_parallel)
  File "/home/zgm/Lufei/MCD_DA/segmentation/models/model_util.py", line 51, in get_models
    model_list = get_MCD_model_list()
  File "/home/zgm/Lufei/MCD_DA/segmentation/models/model_util.py", line 41, in get_MCD_model_list
    model_g = DRNSegBase(model_name=net_name, n_class=n_class, input_ch=input_ch)
  File "/home/zgm/Lufei/MCD_DA/segmentation/models/dilated_fcn.py", line 109, in __init__
    pretrained=pretrained, num_classes=1000, input_ch=input_ch)
  File "/home/zgm/Lufei/MCD_DA/segmentation/models/drn.py", line 343, in drn_d_105
    model.load_state_dict(model_zoo.load_url(model_urls['drn-d-105']))
  File "/home/zgm/.conda/envs/pytorch1.1/lib/python3.6/site-packages/torch/hub.py", line 439, in load_state_dict_from_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/zgm/.conda/envs/pytorch1.1/lib/python3.6/site-packages/torch/hub.py", line 354, in _download_url_to_file
    u = urllib.request.urlopen(req).read()
  File "/home/zgm/.conda/envs/pytorch1.1/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/zgm/.conda/envs/pytorch1.1/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/zgm/.conda/envs/pytorch1.1/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/zgm/.conda/envs/pytorch1.1/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/zgm/.conda/envs/pytorch1.1/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/zgm/.conda/envs/pytorch1.1/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`
So can you provide the drn_d_105-12b40979.pth, thanks so much！

**Comment by liqy2019** [comment]
同样的问题，drn_d_105-12b40979.pth无法下载

**Comment by liqy2019** [comment]
我在其他网站上找到了drn_d_105-12b40979.pth，如果需要这个，可以联系我：411376092@qq.com

**Comment by DeveloperZWK** [comment]
you can set webroot = 'http://dl.yf.io/drn/'
